### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019'

### ISSUE THREAD

**Issue by eliasah** [zero323/airship-convert#5]
```
eliasah@AH-PC:~/utils/zeppelin$ airship-convert extract notebooks/* --output snippets/
Traceback (most recent call last):
  File "/home/eliasah/anaconda2/bin/airship-convert", line 9, in <module>
    main()
  File "/home/eliasah/anaconda2/lib/python2.7/site-packages/airship_convert/__init__.py", line 37, in main
    args.func(args)
  File "/home/eliasah/anaconda2/lib/python2.7/site-packages/airship_convert/pipelines/__init__.py", line 62, in extract_func
    return process(args.paths, load_zeppelin_for_path, tag_and_strip_annotations(args.language), filter_, sink_)
  File "/home/eliasah/anaconda2/lib/python2.7/site-packages/airship_convert/pipelines/__init__.py", line 34, in process
    pipe(path, load_, transform_, filter_, sink_)
  File "/home/eliasah/anaconda2/lib/python2.7/site-packages/toolz/functoolz.py", line 518, in pipe
    data = func(data)
  File "/home/eliasah/anaconda2/lib/python2.7/site-packages/toolz/functoolz.py", line 281, in __call__
    return self._partial(*args, **kwargs)
  File "/home/eliasah/anaconda2/lib/python2.7/site-packages/airship_convert/render/source.py", line 31, in render_source
    render_source_(notebook, output_file, template)
  File "/home/eliasah/anaconda2/lib/python2.7/site-packages/airship_convert/render/source.py", line 21, in render_source_
    fw.write(template.render(notebook))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 1318: ordinal not in range(128)
```

**Comment by zero323** [comment]
I have a problem with reproducing that. Could you take a look at cff7912b01cfe0911af190981044fad9c0f41c18 and check if it resolves the issue.
